### ISSUE TITLE
clang-tidy doesn't recognize PCH format

### ISSUE THREAD

**Issue by mo-xiaoming** [cpp-best-practices/cpp_starter_project#25] opened 2020-03-02 12:46 UTC
Built with  both `ENABLE_CLANG_TIDY` and `DENABLE_PCH=ON` enabled, clang-tidy threw errors about PCH format unrecognized

```
error: file '.../build/test/CMakeFiles/tests.dir/cmake_pch.hxx.gch' is not a valid precompiled PCH file [clang-diagnostic-error]
error: input is not a PCH file: '.../build/test/CMakeFiles/tests.dir/cmake_pch.hxx.gch' [clang-diagnostic-error]
2 errors generated.
Error while processing .../test/tests.cpp.
Found compiler error(s).
```

```
$ clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 9.0.0
  
  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: ivybridge
```

P.S. I tried to limit clang-tidy to specified targets, but PCH file implicitly included in all cpp files, so this way a dead end

**Comment by exief** [comment] 2020-03-09 06:16
It's caused by gch being a gcc specific extension for pch files, clang expects it to be a .pch file not sure how to resolve this

**Comment by balintkissdev** [comment] 2021-04-21 19:17
I saw your issue while I was also having this problem in my project and was scouring Google for help. If anyone else has this same issue with clang-tidy + pch + gcc, I found a workaround by generating the clang `.pch` as a custom command before making the real build with the gcc `.gch`.

https://gitlab.kitware.com/cmake/cmake/-/issues/22081#note_943104

**Comment by lefticus** [comment] 2022-03-17 23:52
A fix has been applied in https://github.com/cpp-best-practices/project_options to prevent PCH with GCC + clang-tidy being enabled at the same time.

**Closed by lefticus** 2022-03-17 23:52 UTC
