### ISSUE TITLE
Builds fail for CMake < 3.18

### ISSUE THREAD

**Issue by joeperri95** [cpp-best-practices/cpp_starter_project#208] opened 2022-03-30 21:01 UTC
Recently a change was put in to use the package_project function from the [project_options](https://github.com/aminya/project_options) library. 

This function asserts the policy CMP0103 which was introduced in CMake 3.18

This is causing builds to fail for CMake 3.16 which is the currently defined minimum ~~and is what is available in the docker environment.~~

It looks like this was addressed in main branch of project_options but there is no release yet.

**Comment by aminya** [comment] 2022-03-31 02:20
There is already a condition to skip this policy check on older CMake. 

https://github.com/aminya/project_options/blob/main/src/PackageProject.cmake#L8

**Comment by joeperri95** [comment] 2022-03-31 14:35
Not saying that there is any problem with project_options just that it will not work for CMake < 3.18 with the latest release v0.19.0. The policy skip has not yet been included in a published release so the maintainer of this project can't just bump a version number yet.

For the record your template project will have the same issue for CMake < 3.18.

**Comment by ddalcino** [comment] 2022-03-31 20:43
Duplicate of: https://github.com/cpp-best-practices/cpp_boilerplate_project/issues/17

Now closing, since it is more appropriate to handle this upstream. If you disagree, I will reopen this.

**Closed by ddalcino** 2022-03-31 20:43 UTC
